/* eslint-disable @next/next/no-css-tags */
import type { Metadata } from 'next'
import { Providers } from '../providers'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { CookiesProvider } from 'next-client-cookies/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Big Code Theory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: string }
}>) {
  return (
    <html lang={params.lang}>
      <head>
        <link href="/public/output.css" rel="stylesheet" />
      </head>
      <body className={`${inter.className} bg-slate-900 h-screen`}>
        <Providers>
          <CookiesProvider>{children}</CookiesProvider>
        </Providers>
      </body>
    </html>
  )
}
